### ISSUE TITLE
NoClassDefFoundError when using getUserSessions Adaptive Function

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#17132]
**Describe the issue:**

It appears that the _getUserSessions_ adaptive authentication function does not work in WSO2 IS v6.0.0 and v6.1.0. The following error occurs when the method is invoked in any authentication step.

```
ERROR {org.wso2.carbon.identity.application.authentication.framework.config.model.graph.JsNashornGraphBuilder} - Error in executing the javascript for service provider : My Account, Javascript Fragment : 
function (context) {
           var user = context.currentKnownSubject;
           var sessions = getUserSessions(user);
       } java.lang.NoClassDefFoundError: org/wso2/carbon/identity/application/authentication/framework/internal/FrameworkServiceDataHolder
	at org.wso2.carbon.identity.conditional.auth.functions.user.model.JsWrapperFactoryProvider.<init>(JsWrapperFactoryProvider.java:35)
	at org.wso2.carbon.identity.conditional.auth.functions.user.model.JsWrapperFactoryProvider.<clinit>(JsWrapperFactoryProvider.java:29)
	at org.wso2.carbon.identity.conditional.auth.functions.user.GetUserSessionsFunctionImpl.getUserSessions(GetUserSessionsFunctionImpl.java:51)
...
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.application.authentication.framework.internal.FrameworkServiceDataHolder cannot be found by org.wso2.carbon.identity.conditional.auth.functions.user_1.2.19
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 69 more
```

**How to reproduce:**

To reproduce the above issue you can utilize a sample adaptive script as shown below with the getUserSessions function and add it to any authentication step.

```
var onLoginRequest = function(context) {
   executeStep(1, {
       onSuccess: function (context) {
           var user = context.currentKnownSubject;  
           var sessions = getUserSessions(user);
       }
   });
};
```

**Environment information**
 - Product Version: v6.0.0, v6.1.0

**Comment by RushanNanayakkara** [comment]
Closing as completed.
