### ISSUE TITLE
Server start fails when FIPS mode is enabled

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#27333]
### Steps to Reproduce

1. Go to bin folder and run `sh fips.sh`
2. Add the following config to deployment.toml

```toml
[jce_provider]
provider_name = "BCFIPS"
```
3. Try to restart the server and it will not start
```
[2026-03-30 15:10:04,305] [] ERROR {Events.Framework} - FrameworkEvent ERRORorg.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.claim.mgt [186]
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.claim.metadata.mgt; version="[5.14.0,8.0.0)"
    -> Export-Package: org.wso2.carbon.identity.claim.metadata.mgt; bundle-symbolic-name="org.wso2.carbon.identity.claim.metadata.mgt"; bundle-version="7.10.110"; version="7.10.110"; uses:="org.wso2.carbon.identity.claim.metadata.mgt.dto,org.wso2.carbon.identity.claim.metadata.mgt.exception,org.wso2.carbon.identity.claim.metadata.mgt.model,org.wso2.carbon.user.api,org.wso2.carbon.user.core.claim,org.wso2.carbon.user.core.claim.inmemory"
       org.wso2.carbon.identity.claim.metadata.mgt [314]
         Unresolved requirement: Import-Package: org.wso2.carbon.identity.event; version="[5.14.0,8.0.0)"
           -> Export-Package: org.wso2.carbon.identity.event; bundle-symbolic-name="org.wso2.carbon.identity.event"; bundle-version="7.10.110"; version="7.10.110"; uses:="org.wso2.carbon.identity.base,org.wso2.carbon.identity.event.bean,org.wso2.carbon.identity.event.event,org.wso2.carbon.identity.event.handler"
              org.wso2.carbon.identity.event [346]
                Unresolved requirement: Import-Package: org.wso2.carbon.identity.core.bean.context; version="[5.14.0,8.0.0)"
                  -> Export-Package: org.wso2.carbon.identity.core.bean.context; bundle-symbolic-name="org.wso2.carbon.identity.core"; bundle-version="7.10.110"; version="7.10.110"
                     org.wso2.carbon.identity.core [332]
                       Unresolved requirement: Import-Package: org.apache.xerces.util; version="[2.12.0,3.0.0)"; resolution:="optional"
                       Unresolved requirement: Import-Package: org.wso2.carbon.core.util; version="[4.5.0,5.0.0)"
                         -> Export-Package: org.wso2.carbon.core.util; bundle-symbolic-name="org.wso2.carbon.core"; bundle-version="4.12.21"; version="4.12.21"; uses:="javax.xml.namespace,org.apache.axiom.om,org.apache.axis2,org.apache.axis2.context,org.apache.axis2.description,org.apache.axis2.engine,org.apache.neethi,org.osgi.framework,org.wso2.carbon,org.wso2.carbon.base.api,org.wso2.carbon.core.security,org.wso2.carbon.crypto.api,org.wso2.carbon.registry.core,org.wso2.carbon.registry.core.service,org.wso2.carbon.registry.core.session,org.wso2.carbon.user.core,org.wso2.carbon.user.core.service"
                            org.wso2.carbon.core [192]
                              Unresolved requirement: Import-Package: org.bouncycastle.jcajce.provider; version="[1.0.0,2.0.0)"; resolution:="optional"
                              Unresolved requirement: Import-Package: org.bouncycastle.jce.provider; version="[1.0.0,2.0.0)"
                Unresolved requirement: Import-Package: org.wso2.carbon.identity.core.handler; version="[5.14.0,8.0.0)"
                  -> Export-Package: org.wso2.carbon.identity.core.handler; bundle-symbolic-name="org.wso2.carbon.identity.core"; bundle-version="7.10.110"; version="7.10.110"; uses:="org.wso2.carbon.identity.base,org.wso2.carbon.identity.core.bean.context"
         Unresolved requirement: Import-Package: org.wso2.carbon.identity.event.event; version="[5.14.0,8.0.0)"
           -> Export-Package: org.wso2.carbon.identity.event.event; bundle-symbolic-name="org.wso2.carbon.identity.event"; bundle-version="7.10.110"; version="7.10.110"
  Unresolved requirement: Import-Package: org.wso2.carbon.core.util; version="[4.5.0,5.0.0)"
    -> Export-Package: org.wso2.carbon.core.util; bundle-symbolic-name="org.wso2.carbon.core"; bundle-version="4.12.21"; version="4.12.21"; uses:="javax.xml.namespace,org.apache.axiom.om,org.apache.axis2,org.apache.axis2.context,org.apache.axis2.description,org.apache.axis2.engine,org.apache.neethi,org.osgi.framework,org.wso2.carbon,org.wso2.carbon.base.api,org.wso2.carbon.core.security,org.wso2.carbon.crypto.api,org.wso2.carbon.registry.core,org.wso2.carbon.registry.core.service,org.wso2.carbon.registry.core.session,org.wso2.carbon.user.core,org.wso2.carbon.user.core.service"
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.claim.metadata.mgt.exception; version="[5.14.0,8.0.0)"
    -> Export-Package: org.wso2.carbon.identity.claim.metadata.mgt.exception; bundle-symbolic-name="org.wso2.carbon.identity.claim.metadata.mgt"; bundle-version="7.10.110"; version="7.10.110"; uses:="org.wso2.carbon.identity.base,org.wso2.carbon.identity.claim.metadata.mgt.util"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2073)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2064)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2006)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1967)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1883)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

### Version

IS 7.3.0-beta

### Developer Checklist

- [ ] [Behavioural Change] Does this change introduce a behavioral change to the product?
- [ ]  ↳ Approved by team lead
- [ ]  ↳ Label `impact/behavioral-change` added
- [ ] [Migration Impact] Does this change have a migration impact?
- [ ]  ↳ Migration label added (e.g., `7.2.0-migration`)
- [ ]  ↳ Migration issues created and linked
- [ ] [New Configuration] Does this change introduce a new configuration?
- [ ]  ↳ Label `config` added
- [ ]  ↳ Configuration is properly documented

**Comment by hwupathum** [comment]
Documentation https://is.docs.wso2.com/en/next/deploy/security/enable-fips-for-is

**Comment by UdeshAthukorala** [comment]
## Root Cause Analysis

When FIPS-compliant mode is enabled, the `bcprov` (BouncyCastle) jar is removed from the plugins folder. However, `org.bouncycastle.jce.provider` is declared as a mandatory import package in the `carbon.core` component, causing OSGi bundle resolution to fail at server startup.

Making the import optional in `carbon.core` resolves the immediate bundle resolution error, but introduces a secondary failure - a `NoClassDefFoundError` for `org/eclipse/equinox/p2/planner/IPlanner`:

```
[2026-04-03 10:15:41,039] ERROR {ComponentMgtCoreServiceComponent} - java.lang.NoClassDefFoundError: org/eclipse/equinox/p2/planner/IPlanner
    at org.wso2.carbon.feature.mgt.core.internal.ServiceHolder.setProvisioningAgentProvider(ServiceHolder.java:140)
```

This is caused by a version bump of `org.eclipse.equinox.p2.artifact.repository` introduced in https://github.com/wso2/carbon-kernel/pull/4433, effective from IS 7.3 onwards, as a part done for provide Java 21 support.

| Version | `org.bouncycastle.jce.provider` dependency |
|---|---|
| `1.1.300.v20131211-1531` (old) | Optional |
| `1.5.300.v20240220` (new) | **Mandatory** |

With the newer version, `org.eclipse.equinox.p2.artifact.repository` fails to activate without BouncyCastle present, and since `IPlanner` lives in that bundle, it becomes unavailable, causing the `NoClassDefFoundError`.

---

## Proposed Solutions

### Solution 1 - Gracefully handle the exception

Catch and gracefully handle the `NoClassDefFoundError` in `ComponentMgtCoreServiceComponent`. Investigation confirms that even when `org.eclipse.equinox.p2.artifact.repository` and related Eclipse Equinox bundles remain in `INSTALLED` state (not activated), the product starts and functions correctly. This is the lower-risk approach since it keeps the FIPS posture intact.

### Solution 2 - Retain `bcprov` jar even in FIPS mode

Avoid removing the `org.bouncycastle.bcprov` jar when FIPS mode is enabled. At runtime, cryptographic operations use only the JCE provider configured in `deployment.toml`, and only that provider is registered as the active security provider at startup.

**Concerns:**
- Retaining `bcprov` in FIPS mode weakens the FIPS boundary guarantee. Future code changes could inadvertently use the BouncyCastle JCE provider even in FIPS environments - for example, the recently bundled bcrypt password hashing algorithm already depends on it. Although bcrypt is disabled by default, its presence means it could be mistakenly enabled in a FIPS deployment. (https://github.com/wso2/product-is/issues/26164)
- Security scanners are likely to flag `bcprov` as a finding even if it is unused at runtime.

### Solution 3 - Downgrade Equinox p2 bundles to versions that do not require BouncyCastle

Downgrade the set of Eclipse Equinox p2-related jars to versions that have no mandatory BouncyCastle dependency while still being compatible with Java 21. This directly eliminates the root cause without any changes to the FIPS configuration or exception handling.

#### Version Changes

| Artifact | Current Version | Downgraded Version |
|---|---|---|
| `equinox.p2.artifact.repository` | `1.5.300` | `1.4.0` |
| `equinox.p2.core` | `2.11.0` | `2.8.0` |
| `equinox.p2.director` | `2.6.300` | `2.5.0` |
| `equinox.p2.director.app` | `1.3.300` | `1.2.0` |
| `equinox.p2.directorywatcher` | `1.4.300` | `1.3.0` |
| `equinox.p2.engine` | `2.10.0` | `2.7.0` |
| `equinox.p2.console` | `1.3.300` | `1.2.0` |
| `equinox.p2.extensionlocation` | `1.5.300` | `1.4.0` |
| `equinox.p2.garbagecollector` | `1.3.200` | `1.2.0` |
| `equinox.p2.jarprocessor` | `1.3.300` | `1.2.0` |
| `equinox.p2.metadata` | `2.9.0` | `2.4.0` |
| `equinox.p2.metadata.repository` | `1.5.300` | `1.4.0` |
| `equinox.p2.reconciler.dropins` | `1.5.300` | `1.4.0` |
| `equinox.p2.repository.tools` | `2.4.300` | `2.3.0` |
| `equinox.p2.repository` | `2.8.100` | `2.5.0` |
| `equinox.p2.touchpoint.eclipse` | `2.4.200` | `2.3.0` |
| `equinox.p2.touchpoint.natives` | `1.5.200` | `1.4.0` |
| `equinox.p2.updatechecker` | `1.4.200` | `1.3.0` |
| `equinox.p2.updatesite` | `1.3.200` | `1.2.0` |
| `equinox.p2.publisher.eclipse` | `1.6.0` | `1.5.0` |
| `equinox.p2.publisher` | `1.9.100` | `1.6.0` |
| `equinox.p2.transport.ecf` | `1.4.400` | `1.2.0` |

**Concern:** The original versions were bumped as part of Java 21 support work via [carbon-kernel PR #4433](https://github.com/wso2/carbon-kernel/pull/4433). Downgrading requires thorough verification that the older versions remain fully functional under Java 21 and do not reintroduce any regressions that the upgrade was intended to fix.

**Comment by UdeshAthukorala** [comment]
After discussing with the team decided to go with the above mentioned approach 3(Downgrade the Equinox dependencies to a version that does not require BouncyCastle as a runtime dependency while still supporting Java 21.) and decide to request a fix from Equinox for this problem as a long term solution:

Related PRs:
- https://github.com/wso2/carbon-kernel/pull/4570
- https://github.com/wso2-extensions/identity-hash-provider-bcrypt/pull/12

**Comment by UdeshAthukorala** [comment]
After Merging the PR integrtion tests against both Java 21 & 25(https://github.com/wso2/product-is/actions/runs/24065359107) was succeessful.

<img width="1728" height="865" alt="Image" src="https://github.com/user-attachments/assets/92e83336-224f-4344-b607-4a236e066781" />
