### ISSUE TITLE
Classloading issues with Duo Connector components in IS 7.x

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#26616]
#### Description

Attempts to deploy the latest **Duo Connector** components (Authenticator and Provisioning Handler) from the [WSO2 Connector Store](https://store.wso2.com/connector/identity-outbound-auth-duo) fail on Identity Server 7.x due to classloading and OSGi resolution errors.

This appears to be related to changes introduced in https://github.com/wso2-extensions/identity-outbound-auth-duo/pull/73. Where WSO2 IS 7.0.0 uses `org.json:3.0.0.wso2v5` but WSO2 IS 7.1.0 uses `org.json:3.0.0.wso2v4`.

The failure manifests differently across the two components:

1. **Duo Authenticator:** Fails to resolve the `org.json` package dependency.
2. **Duo Provisioning Handler:** Fails with a `NoClassDefFoundError` regarding the `AbstractProvisioningConnectorFactory`.

#### Steps to Reproduce

**Scenario A: Duo Connector Authenticator**

1. Download the latest Duo Connector Authenticator (`org.wso2.carbon.extension.identity.authenticator.duo.connector-4.0.15.jar`).
2. Deploy the JAR to the `components/dropins` directory of a WSO2 IS **7.1.0** instance.
3. Start the server.
4. Observe the `BundleException` in `wso2carbon.log`.

<details>
<summary><ins>Stacktrace (Authenticator)</ins></summary>

```java
[2026-01-29 00:54:40,520] [] ERROR {Events.Framework} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.extension.identity.authenticator.duo.connector [218]
  Unresolved requirement: Import-Package: org.json; version="3.0.0.wso2v5"
    ... TRUNCATED FOR BREVITY ...
```

</details>

**Scenario B: Duo Connector Provisioning Handler**

1. Download the latest Duo Provisioning Connector (`org.wso2.carbon.extension.identity.provisioning.duo.connector_1.1.2.jar`).
2. Deploy the JAR to the `components/dropins` directory of a WSO2 IS **7.0.0** or **7.1.0** instance.
3. Start the server.
4. Observe the `NoClassDefFoundError` during component activation.

<details>
<summary><ins>Stacktrace (Provisioning Handler)</ins></summary>

```java
[2026-01-29 00:54:40,555] [] FATAL {org.wso2.carbon.identity.provisioning.duo.internal.DuoConnectorServiceComponent} -  Error while activating duo Identity Provisioning Connector java.lang.NoClassDefFoundError: org/wso2/carbon/identity/provisioning/AbstractProvisioningConnectorFactory
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
    at org.wso2.carbon.identity.provisioning.duo.internal.DuoConnectorServiceComponent.activate(DuoConnectorServiceComponent.java:57)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    ... TRUNCATED FOR BREVITY ...
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.provisioning.AbstractProvisioningConnectorFactory cannot be found by org.wso2.carbon.extension.identity.provisioning.duo.connector_1.1.2
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
    ... TRUNCATED FOR BREVITY ...

```

</details>

#### Expected Behavior

Both connector components should resolve their dependencies (specifically `org.json` and `AbstractProvisioningConnectorFactory`) and activate successfully on IS 7.x, consistent with previous versions.

### Please select the area issue is related to

Identity Server Core

### Version

IS 7.0.0, IS 7.1.0

### Environment Details (with versions)

N/A

### Developer Checklist

- [ ] [Behavioural Change] Does this change introduce a behavioral change to the product?
- [ ]  ↳ Approved by team lead
- [ ]  ↳ Label `impact/behavioral-change` added
- [ ] [Migration Impact] Does this change have a migration impact?
- [ ]  ↳ Migration label added (e.g., `7.2.0-migration`)
- [ ]  ↳ Migration issues created and linked
- [ ] [New Configuration] Does this change introduce a new configuration?
- [ ]  ↳ Label `config` added
- [ ]  ↳ Configuration is properly documented

**Comment by KD23243** [comment]
Closing the issue as both connectors have been released.
