### ISSUE TITLE
Cipher-tool build failure in OpenJDK 11

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#14793]
**Describe the issue:**
Cipher tool fails to build using OpenJDK 11, although it is build in OpenJDK 1.8

**How to reproduce:**
Try to build the [cipher-tool](https://github.com/wso2-support/cipher-tool) using `mvn clean install` in a Java 11 environment

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /cipher-tool/components/ciphertool/src/main/java/org/wso2/ciphertool/CipherTool.java:[33,22] package javax.xml.bind does not exist
[ERROR] /cipher-tool/components/ciphertool/src/main/java/org/wso2/ciphertool/utils/Utils.java:[34,22] package javax.xml.bind does not exist
[ERROR] /cipher-tool/components/ciphertool/src/main/java/org/wso2/ciphertool/utils/Utils.java:[407,28] cannot find symbol
  symbol:   variable DatatypeConverter
  location: class org.wso2.ciphertool.utils.Utils
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WSO2 Cipher Tool - Parent 1.1.9.4-SNAPSHOT:
[INFO] 
[INFO] WSO2 Cipher Tool - Parent .......................... SUCCESS [  0.362 s]
[INFO] WSO2 Cipher Tool ................................... FAILURE [  0.565 s]
[INFO] WSO2 Cipher Tool for User Stores ................... SKIPPED
[INFO] Cipher Tool Feature ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.994 s
[INFO] Finished at: 2022-08-25T15:52:25+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project org.wso2.ciphertool: Compilation failure: Compilation failure: 
[ERROR] /cipher-tool/components/ciphertool/src/main/java/org/wso2/ciphertool/CipherTool.java:[33,22] package javax.xml.bind does not exist
[ERROR] /cipher-tool/components/ciphertool/src/main/java/org/wso2/ciphertool/utils/Utils.java:[34,22] package javax.xml.bind does not exist
[ERROR] /cipher-tool/components/ciphertool/src/main/java/org/wso2/ciphertool/utils/Utils.java:[407,28] cannot find symbol
[ERROR]   symbol:   variable DatatypeConverter
[ERROR]   location: class org.wso2.ciphertool.utils.Utils
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

```

**Environment information**
 - Java version: OpenJDK 11.0.16.1

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
